name: middle
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.3

  provider: ^4.1.3
  shared_preferences: ^0.5.7+2
  image_picker: ^0.6.6+5
  uuid: ^2.0.4

  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.16.1
  firebase_storage: ^3.1.6
  firebase_messaging: ^6.0.16
  cloud_firestore: ^0.13.5
  
  cache_image: ^1.0.5
  cached_network_image: ^2.2.0+1

  bubble: ^1.1.9+1
  intro_slider: ^2.2.9
  intl_phone_number_input: ^0.4.2
  easy_localization: ^2.3.2
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
    - lang/
